#!/bin/sh
rm *.tga
rm *.bmp
echo "test scene 0~9"

./a4 -input input/scene01_plane.txt  -size 200 200 -output output/1.bmp
./a4 -input input/scene02_cube.txt  -size 200 200 -output output/2.bmp
./a4 -input input/scene03_sphere.txt  -size 200 200 -output output/3.bmp
./a4 -input input/scene04_axes.txt  -size 200 200 -output output/4.bmp
./a4 -input input/scene05_bunny_200.txt  -size 200 200 -output output/5.bmp
./a4 -input input/scene06_bunny_1k.txt  -size 200 200 -output output/6.bmp
./a4 -input input/scene07_shine.txt  -size 200 200 -output output/7.bmp
./a4 -input input/scene08_c.txt -size 200 200 -output output/8.bmp
./a4 -input input/scene09_s.txt -size 200 200 -output output/9.bmp
